version: "3.7"

services:
  database:
    image: postgres:latest
    ports:  
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
      - ./test:/var/lib/postgresql/test
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}